### ISSUE TITLE
ValueError: The extension does not support current version od JupyterLab

### ISSUE THREAD

**Issue by juansec** [jupyterlab/jupyterlab-github#100]
`jupyter labextension install @jupyterlab/git` brings me:
An error occured.
ValueError: The extension "@jupyterlab/git" does not yet support the current version of JupyterLab.
Conflicting Dependencies:
JupyterLab       ---       Extension    ---     Package
>=2.1.0 <2.2.0    ---      >=1.1.0 <2.0.0  ---  @jupyterlab/application
>=2.1.0 <2.2.0   ---       >=1.1.0 <2.0.0   --- @jupyterlab/apputils
>=2.1.0 <2.2.0       ---   >=1.1.0 <2.0.0    ---@jupyterlab/console
>=4.1.0 <4.2.0         --- >=3.1.0 <4.0.0    ---@jupyterlab/coreutils
>=2.1.0 <2.2.0     ---     >=1.1.0 <2.0.0   --- @jupyterlab/filebrowser
>=5.1.0 <5.2.0         --- >=4.1.0 <5.0.0   --- @jupyterlab/services
>=2.1.0 <2.2.0       ---   >=1.1.0 <2.0.0  ---  @jupyterlab/terminal
>=16.9.0 <16.10.0   ---    >=16.8.4 <16.9.0 --- react
>=16.9.0 <16.10.0      --- >=16.8.4 <16.9.0 --- react-dom

is this extension working??

**Comment by ian-r-rose** [comment]
Your error message appears to be referring to `@jupyterlab-git`, which is different from this extension. It also has gotten a 2.0-compatible release since then, I believe. Closing as fixed/not relevant to this repo.
