### ISSUE TITLE
Add releaser tokens to the repo

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab-github#147]
As a follow-up to https://github.com/jupyterlab/jupyterlab-github/pull/145, we will be making a new release of the extension that is compatible with JupyterLab 4.

Currently the repo does not have any token in the GitHub Actions secrets:

![image](https://github.com/jupyterlab/jupyterlab-github/assets/591645/4de98a8a-ee95-4951-862e-eefe30763679)

Which means using the workflows from the repo and https://github.com/jupyterlab-bot will likely not work.

If `jupyterlab-github` is already configured to support the trusted publisher on PyPI, we could also use this instead of the PyPI release token.

cc @blink1073 @fcollonval @JasonWeill who I think have access to the shared vault. If you can help with this that would be great, thanks! I don't have access to the bot tokens.

**Comment by blink1073** [comment]
I added the trusted publisher integration and the NPM token, working on admin github token now:

<img width="621" alt="image" src="https://github.com/jupyterlab/jupyterlab-github/assets/2096628/dd87a4f2-c215-4323-973d-ee13b9854c4d">

**Comment by blink1073** [comment]
Okay, should be ready:

<img width="296" alt="image" src="https://github.com/jupyterlab/jupyterlab-github/assets/2096628/8b8ca4c6-e090-4d1c-95a4-7d2e44164b07">

**Comment by jtpio** [comment]
Thanks!

I'll try running the workflows now.

**Comment by jtpio** [comment]
Looks like the workflow was missing:

```
permissions:
      id-token: write
```

![image](https://github.com/jupyterlab/jupyterlab-github/assets/591645/579103f5-12f5-4285-b241-6b60db56bfd2)


Will add it and start again.

**Comment by jtpio** [comment]
Now the error is:

```
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://pypi.org/_/oidc/github/mint-token
```

![image](https://github.com/jupyterlab/jupyterlab-github/assets/591645/20f1e410-1319-43c3-bd4c-8f0999b864dc)

**Comment by fcollonval** [comment]
This means that the package on PyPI is not configure to use a trusted publisher.

Someone with enough rights on https://pypi.org/project/jupyterlab-github/ should do it, or you should comment the id token and add a PyPI token.

**Comment by jtpio** [comment]
From https://github.com/jupyterlab/jupyterlab-github/issues/147#issuecomment-1662478834:

> I added the trusted publisher integration and the NPM token, working on admin github token now:
> <img alt="image" width="621" src="https://user-images.githubusercontent.com/2096628/257871522-dd87a4f2-c215-4323-973d-ee13b9854c4d.png">

Could it be because of a workflow name mismatch?

**Comment by blink1073** [comment]
Yes, the workflow name must be the same, I updated it.  The workflow also needs to be set to run in the release environment (which will have to be created and configured in the workflow):

<img width="502" alt="image" src="https://github.com/jupyterlab/jupyterlab-github/assets/2096628/e376cf8c-710a-4d4e-bf7e-89a206258689">

**Comment by jtpio** [comment]
Thanks @blink1073!

Looks like it worked this time after adding the environment to the workflow (https://github.com/jupyterlab/jupyterlab-github/pull/152): https://pypi.org/project/jupyterlab-github/4.0.0/

Closing as fixed.
