### ISSUE TITLE
Tab is missing name

### ISSUE THREAD

**Issue by michaelaye** [jupyterlab/jupyterlab-github#18]
I'm running this extension successfully in a py36 conda env, with this minor hiccup that the tab name is blank:

![screenshot 2017-11-12 22 07 30](https://user-images.githubusercontent.com/69774/32710512-e98e5b08-c7f5-11e7-825a-c9299c240f1c.png)

My installed `jupyter` related versions are:

```bash
(stable) └─❱❱❱ conda list jupyter                                         +7004 22:06 ❰─┘
# packages in environment at /Users/klay6683/miniconda3/envs/stable:
#
jupyter                   1.0.0                    py36_0    conda-forge
jupyter_client            5.1.0                    py36_0    conda-forge
jupyter_console           5.2.0                    py36_0    conda-forge
jupyter_contrib_core      0.3.3                    py36_0    conda-forge
jupyter_contrib_nbextensions 0.3.3                    py36_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyter_highlight_selected_word 0.1.0                    py36_0    conda-forge
jupyter_latex_envs        1.3.8.2                  py36_1    conda-forge
jupyter_nbextensions_configurator 0.2.8                    py36_0    conda-forge
jupyterlab                0.29.1                   py36_0    conda-forge
jupyterlab-github         0.2.0                     <pip>
jupyterlab_launcher       0.5.5                    py36_0    conda-forge
```

**Comment by ian-r-rose** [comment]
Hmm, the intention is that it should be the GitHub logo. Can you check the console to see if there are any 404 errors? Perhaps the server cannot find the image for some reason.

**Comment by michaelaye** [comment]
I should emphasize that I'm using Safari, while most Jupyter devs are Chrome users, I recall? Checking ....

**Comment by michaelaye** [comment]
Is it maybe this?

![screenshot 2017-11-12 22 43 53](https://user-images.githubusercontent.com/69774/32711197-01a8de3e-c7fb-11e7-8aea-7244e21aba05.png)

**Comment by michaelaye** [comment]
It also doesn't work in Chrome, its console is a bit more informative:

![screenshot 2017-11-12 22 46 33](https://user-images.githubusercontent.com/69774/32711263-63bec886-c7fb-11e7-8677-0a843ce0bc2f.png)

**Comment by ian-r-rose** [comment]
The matplotlib/widget errors seem unrelated to me, but it looks like those last two `404`s might be our problem. There is supposed to be an image in the filebrowser pane if you have an invalid user name. Is that also missing?

**Comment by michaelaye** [comment]
Do you mean the filebrowser pane for this GH extension? When I provide a non-existing GH user-name I do not see any icon either in the tab. However, I don't see another failed resource request in the console? Only error messages related to the non-existing GH user.

**Comment by ian-r-rose** [comment]
It should look something like this with an invalid user name:
![image](https://user-images.githubusercontent.com/5728311/32711723-4ddc331a-c7f5-11e7-848e-f6504bff9fd1.png)
If not, it seems that the references to the images are incorrect. I'm not sure what to suggest right now, other than trying a fresh reinstall.

**Comment by michaelaye** [comment]
I don't have that icon, just that text.

**Comment by michaelaye** [comment]
a recent recompile of extensions brought the icon back. but, it actually might have been related to another bug I found https://github.com/jupyterlab/jupyterlab/issues/3263
and it's culprit https://github.com/matplotlib/jupyter-matplotlib/blob/e70968e56b5bd581c0b9d2e9e5d41f9e41e41ffa/js/src/index.js#L8

Anyhow, since ipympl 0.1.0 the icon is now there, related or not.

**Comment by ian-r-rose** [comment]
Glad to hear it!
