### ISSUE TITLE
Private Repository Access?

### ISSUE THREAD

**Issue by rlizzo** [jupyterlab/jupyterlab-github#23]
Hi All, 

I have installed the jupyterlab-github client and serverside extension as per the instructions in the ReadMe. The application is working great, but I am not able to access (or even view) my private repositories. Is private repository access currently supported, or in the works (hopefully)? 

Thanks! 
-Rick

**Comment by ian-r-rose** [comment]
Hi @rlizzo, private repository access is not currently supported. In order to do this, we would probably need to set it up as a full-fledged OAuth application (as opposed to the impoverished sort that it currently is). This is something that we would like to get up and running, but there is nothing in the works for it at the moment.

**Comment by rlizzo** [comment]
Thanks for the quick reply!

**Comment by ian-r-rose** [comment]
I think you are right about the access tokens @dhirschfeld. 

It's not well documented, but from my experimentation, it seems like the *public* `user/repos` endpoint works on both orgs and individual users, so that is what is used in this extension. Do you think it is different for enterprise?

**Comment by ian-r-rose** [comment]
I take back what I said above. @dhirschfeld is completely right, that we need to use two different endpoints to get at public/private repos for organizations and for users. We would still like the frontend to behave the same for both, so it will be kind of tricky, but I think we can do a flow that does something like:
1. Check `/user` to see if there is a user currently authenticated with a personal access token.
2. If yes, to to `/users/repos?affiliation=owner...`
3. If no: check `orgs/<ORGANIZATION>`
4. If that fails, then we are looking at another user. Check `users/<USERNAME>/repos`

It will be more complex, and require more requests to the server, but I think it is worth it to get private repo access.

**Comment by dhirschfeld** [comment]
Yeah, it's a pain that the `users/:username/repos` endpoint doesn't just have a flag to control repo visibility:
![image](https://user-images.githubusercontent.com/881019/38839433-f02f28a0-421d-11e8-9244-a44075351684.png)

AFAICS listing private repos therefore entails knowing the *type* of user/org you're trying to list which will significantly complicate the implementation. Nothing is impossible though...

**Comment by ian-r-rose** [comment]
Once #47 is merged, I think I should be able to do the necessary stuff on the frontend to make it work with private repos.
