### ISSUE TITLE
Github logo coloring

### ISSUE THREAD

**Issue by vidartf** [jupyterlab/jupyterlab-github#30]
Using lab themes, the github logo can sometimes be hard to make out against the background. If possible, it would be better to use an SVG logo styled with CSS (https://css-tricks.com/cascading-svg-fill-color/).

PS: This also holds for the google drive logo in the driver extension.

**Comment by ian-r-rose** [comment]
I agree! The reason I have not done this already is that the terms of service for using the GitHub logos/marks to advertise integration forbids any modification/theming of them: https://github.com/logos. This goes for the Google Drive logo as well.

I am open to ideas for workarounds, though.

**Comment by vidartf** [comment]
Given those rules, the only viable option I see would be to have some JS logic select whether to use the light or dark version of the logo. Suggested outline for logic:
 - Have the JLab theme manager expose a "themeChanged" signal that can be listened to.
 - Get the color of the theme, e.g.: `window.getComputedStyle(document.documentElement).getPropertyValue('--jp-ui-font-color1');`
 - Calculate the color contrast between the theme color and the two logo colors, and use the one with the smallest contrast. Alternatively, get the theme background color and use the logo with the highest color contrast to the background.

Here is a gist for getting the WCAG constrast ratio: https://gist.github.com/vidartf/0f48573f5a4d83c269c883220ab81aa1

**Comment by ian-r-rose** [comment]
Yes, something like this could work (at least for GitHub, which provides another logo color).

**Comment by ian-r-rose** [comment]
Fixed by #67
