### ISSUE TITLE
Support GitHub Enterprise

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/jupyterlab-github#34]
It would be nice if you could hook this extension up to GHE!

It seems this could perhaps be done by simply making `GITHUB_API` (and possibly `GITHUB_BASE_URL`) configurable:

https://github.com/jupyterlab/jupyterlab-github/blob/4f11da60ae61d847f709070e3ffdee58159e9aca/jupyterlab_github/__init__.py#L17

https://github.com/jupyterlab/jupyterlab-github/blob/945d7d6d4ffc8716c307966fe34227fffbf7f555/src/github.ts#L13

https://github.com/jupyterlab/jupyterlab-github/blob/f94d5120b6d22beeeacd8e300aef9b2fc676c26b/src/browser.ts#L41

**Comment by ian-r-rose** [comment]
@dhirschfeld Sorry to be slow, I thought I had already responded, but perhaps left a comment unsent.

I agree that it would be nice to support GHE. I personally do not have access to any GHE accounts, so it would be tricky for me to test and verify. If I were to open a WIP PR with this, would you be able to test if it works?

**Comment by ian-r-rose** [comment]
Fixed by #47.
