### ISSUE TITLE
Support more than 30 repos per user/org

### ISSUE THREAD

**Issue by vidartf** [jupyterlab/jupyterlab-github#35]
Typing in my username in the username field, I only gets the first 30 repositories. This is irrespective of sorting order.

Edit: If I type in `minrk`, I only get to repo names starting with 'b' before being cut off ;)

**Comment by ian-r-rose** [comment]
That sounds like the server extension is not installed, or not working properly. The client-side implementation does not perform any depagination (and results are limited to 30 at a time), but the serverextension does the depagination automatically.

Can you check if there are any warnings to that effect on the Javascript console?

**Comment by vidartf** [comment]
You're right, I just installed the npm package!
