### ISSUE TITLE
Non-English characters. Problem with Encoding.

### ISSUE THREAD

**Issue by Skaarj7** [jupyterlab/jupyterlab-github#39]
There is a wrong text encoding if you try to open any file with non-english characters like russian or japanese. You can see that in README.md for github-repository on russian here: Skaarj7/netology or on japanese: gogotanaka/Primes. Just trash instead of cyrillic symbols or hieroglyphs.
![screen](https://user-images.githubusercontent.com/19416756/37820825-e5cf04aa-2e92-11e8-996f-faedd6b0dba5.JPG)

**Comment by ian-r-rose** [comment]
Thanks for the report @Skaarj7!

**Comment by ian-r-rose** [comment]
Hi @Skaarj7, I've just published a patch release that fixes this. Feel free to comment here if it doesn't work for you.
