### ISSUE TITLE
unusable link generated from relative paths inside notebooks

### ISSUE THREAD

**Issue by jhgoebbert** [jupyterlab/jupyterlab-github#57]
Hello,

thanks for the great extension. It plays an important role for our cluster-wide installation of JupyterHub/JupyterLab and allows users to browse example notebooks easily.

These example notebooks often include links to other notebooks in the same github repository in Markdown cells like this:

`* [Notebook Basics](examples/Notebook/Notebook Basics.ipynb)`
`* [IPython - beyond plain python](examples/IPython Kernel/Beyond Plain Python.ipynb)`
`* [Markdown Cells](examples/Notebook/Working With Markdown Cells.ipynb)`

This will lead to a generated but wrong/damaged link like this:
`github:<notebook-path-on-github>/<relative-path-to-file>`

This is also relevant, if notebooks refer to images, which are part of the repository.

Best,
Jens Henrik

**Comment by ian-r-rose** [comment]
Good point, thanks for the report @jhgoebbert!

**Comment by ian-r-rose** [comment]
Hi @jhgoebbert, we just merged a fix for this upstream, which should be available in the next release.

**Comment by ian-r-rose** [comment]
Fixed upstream.

**Comment by jhgoebbert** [comment]
Thanks!
