### ISSUE TITLE
c.GitHubConfig.access_token is not recognized as the name of a cmdlet, function, script file, or operable program.

### ISSUE THREAD

**Issue by Aurora817** [jupyterlab/jupyterlab-github#59]
I have done step by step according to this code file, installed labextension and got my personal access token from Github. 
While in the step 3. after installing jupyter_github, generating a configuration file named jupyter_notebook_config.py in my directory and run this file, when I type in  c.GitHubConfig.access_token = '< ACCESS_TOKEN >', it returned an error message.

**Code:**
PS C:\Users\Username\.jupyter> jupyter labextension install @jupyterlab/github

PS C:\Users\Username\.jupyter> pip install jupyterlab_github
PS C:\Users\Username\.jupyter> jupyter serverextension enable --sys-prefix jupyterlab_github

Then generated jupyter_notebook_config.py in the directory of PS C:\Users\Username\.jupyter

PS C:\Users\Username\.jupyter> c.GitHubConfig.access_token = '< YOUR_ACCESS_TOKEN >'

**Error Return:**
c.GithubConfig.access_token : The term 'c.GitHubConfig.access_token' is not recognised as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name. or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ c.GitHubConfig.access_token = '< dsfsddsgxxxxxxxx >'
+~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   + CategoryInfo : ObjectNotFound: (c.GitHubConfig.access_token:String) [], CommandNotFoundException
   + FullyQualifiedErrorId: CommanNotFoundException

Thank you!!!

**Comment by Aurora817** [comment]
Hi @ian-r-rose  Thank you!!!

**Comment by ian-r-rose** [comment]
Closing as answered.
