### ISSUE TITLE
[Question] Anyway to change refresh duration in file browser

### ISSUE THREAD

**Issue by ktong** [jupyterlab/jupyterlab-github#64]
For content from github, it really does not need refresh every 10 seconds. 

As we have more than 1000 repos in an org, the list always changed back to repos of org even user enter a repo because the request of repos in org is longer than 10 sec.

**Comment by ian-r-rose** [comment]
This is a good question! I think this could be a setting in the filebrowser widget within the core of JupyterLab.

**Comment by ktong** [comment]
I checked code of fileBrowser and it seems hard coded the refresh durations

**Comment by ian-r-rose** [comment]
Yes it is. But we can make a PR there to make it one of the constructor options for the browser. I think it is reasonable for different browsers to have different refresh intervals, since as you point out, they may have very different network characteristics.

**Comment by ian-r-rose** [comment]
@ktong I've made a PR to the core of JupyterLab with this option. What do you think a reasonable refresh interval for the GitHub browser might be? 30 seconds? 60?

**Comment by ktong** [comment]
I prefer 10 minutes. there is no much change in Github need refresh immediately.

**Comment by ian-r-rose** [comment]
Fixed by #67.
