### ISSUE TITLE
Rename drive.json

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/jupyterlab-github#66]
To be something more specific/recognisable.

https://github.com/jupyterlab/jupyterlab-github/blob/master/schema/drive.json

I'd suggest `github.json` would better reflect the contents of the file.

**Comment by dhirschfeld** [comment]
It looks like it get's own `github` folder so this isn't really necessary.

**Comment by ian-r-rose** [comment]
I agree that `drive.json` is not the best name. We could change it as you suggest, at the cost of breaking existing settings files that are already in the wild. I'm not sure whether that would cause more confusion than the status quo.

**Comment by dhirschfeld** [comment]
I wouldn't break existing settings for this since it does get it's own github folder so is un-ambiguous.
