### ISSUE TITLE
jupyter labextension list showing github extension as "disabled"

### ISSUE THREAD

**Issue by VivekVetri** [jupyterlab/jupyterlab-github#76]
Followed the instructions in the README. "jupyter labextension list" command shows github is disabled. Tried enabling with "jupyter serverextension enable --py jupyterlab_github". No luck. Any help would be appreciated. 

<img width="823" alt="screen shot 2019-01-16 at 10 03 59 pm" src="https://user-images.githubusercontent.com/1858818/51294922-c0d10700-19da-11e9-81e5-94e377822a7d.png">

Version details : -

OS - MacOS Mojave
Jupyter Notebook version - 5.6.0
Jupyter Lab version - 0.35.4
Jupyter Hub version - 0.9.4

**Comment by ian-r-rose** [comment]
Hi @VivekVetri, the extension has both a server side and a client side component. It looks like the client side is disabled (though I'm not sure how it got that way -- perhaps from an older install?).

You can reenable that by entering
```bash
jupyter labextension enable @jupyterlab/github
```

**Comment by ian-r-rose** [comment]
Closing as answered, but if this did not fix the issue, feel free to comment further and we can reopen.
