### ISSUE TITLE
compatibility issue with jupyter lab version 1.0.0a1

### ISSUE THREAD

**Issue by kiranik** [jupyterlab/jupyterlab-github#79]
I installed Jupyter lab in developer mode(version=1.0.0a1). and tried to install jupyterlab-github from extensions manager in jupyter lab. It is causing the following compatibility errors.:
**An error occurred installing @jupyterlab/github.

Error message:

No version of @jupyterlab/github could be found that is compatible with the current version of JupyterLab.

Conflicting Dependencies:
JupyterLab              Extension              Package
>=1.0.0-alpha.3 <2.0.0  >=0.19.1 <0.20.0       @jupyterlab/filebrowser
>=1.0.0-alpha.3 <2.0.0  >=0.19.1 <0.20.0       @jupyterlab/docmanager
>=1.0.0-alpha.3 <2.0.0  >=0.19.1 <0.20.0       @jupyterlab/apputils
>=1.0.0-alpha.3 <2.0.0  >=0.19.1 <0.20.0       @jupyterlab/application**
<img width="1649" alt="screen shot 2019-02-20 at 1 27 22 pm" src="https://user-images.githubusercontent.com/6435143/53075598-990e1b00-3513-11e9-84b1-e77b1602cd09.png">

**Comment by ian-r-rose** [comment]
Sorry for the slow response @kiranik. I've just published a prerelease that works with the newest JupyterLab (1.0a3). Closing this as fixed, but let me know if you run into any trouble and we can reopen.

**Comment by gnestor** [comment]
You can upgrade to this latest version with ` jupyter labextension install @jupyterlab/github@next`
