### ISSUE TITLE
[Design question] Why not simply git clone the repositories?

### ISSUE THREAD

**Issue by amit1rrr** [jupyterlab/jupyterlab-github#84]
@ian-r-rose @dhirschfeld 
We're building a similar plugin for GitLab and had a couple of questions about design choices you made in this repo. We would be grateful if you could answer some of these as it'll set us on the right path.

- I see that you are fetching repository contents via GitHub API and converting them into Jupyter models (Contents.IModel etc.). Why not simply run a git clone from the server extension? That way the contents would be available under the regular file browser of Jupyter

- Are the repository contents backed on disk somewhere? Does the refresh from repo overwrite the local edits?

- I'm wondering if we were to go git clone way, how hard/easy would it be to later support 2-way synch (commit/push to repo etc.). Maybe we could read the repository state on disk and allow users to do git add/commit/push etc. Maybe use the [git extension](https://github.com/jupyterlab/jupyterlab-git) on the top. 

Feel free to mention anything else I should be aware of. Thanks for your time!

**Comment by dhirschfeld** [comment]
You might just want to browse a particular notebook?
If you want to clone an entire repo, why not just use `jupyterlab-git`?

It would be nice for this extension to be have a clone button, the implementation of which could be delegated to the `jupyterlab-git` extension.

**Comment by amit1rrr** [comment]
> You might just want to browse a particular notebook?
ah, makes sense. So any edits made to notebooks under this plugin are not persisted anywhere? Not even locally on the disk?

> If you want to clone an entire repo, why not just use jupyterlab-git?
Yeah that's a good idea. We wanted to preload the jupyter instance with user's GitLab repositories but that can be done without an extension (as a postStart lifecycle hook after spawning from JupyterHub). We'll just have to set the access_tokens properly.

**Comment by ian-r-rose** [comment]
@amit1rrr Sorry for not responding to this sooner, I've been looking through the work you did on setting up the GitLab JupyterHub deployment with this stuff, and I'm impressed! I've started to do some simliar things in a JupyterHub deployment: https://github.com/CityOfLosAngeles/citywide-jupyterhub/blob/e010e49cf02ef42c4c9a237b6e9bc33d6a344288/deploy/config.yaml#L18-L42

But to reiterated what @dhirschfeld said, this extension is mostly oriented around browsing remote repositories, and is explicitly *not* about making edits, commits, or any version-control operations. That said, a clone button would be nice.

**Comment by amit1rrr** [comment]
Thanks @ian-r-rose. We ended up using the jupyterlab-git extension for GitLab setup. Works very well.

Your work looks very interesting as well. Do you actually plan to have a public citywide JupyterHub deployment? If yes, that's very interesting and I'm really curious so I'll throw a few questions out there,

- How do you plan to tackle abuse (e.g. mining crypto)?  
- Who is paying for the underlying compute infrastructure?

> https://github.com/CityOfLosAngeles/citywide-jupyterhub/blob/e010e49cf02ef42c4c9a237b6e9bc33d6a344288/deploy/config.yaml#L18-L42

By the way, @minrk helped a lot to get this setup going :)
