### ISSUE TITLE
Private repos in organization I have access to are not listed (only public ones)

### ISSUE THREAD

**Issue by memeplex** [jupyterlab/jupyterlab-github#91]
This seems to be fixed in https://github.com/jupyterlab/jupyterlab-github/pull/48 but not for me...

I have access to all private repositories in an organization. I have created an access token (for my user, not for the organization) with full repo permissions and added it to jupyter as described in your README:

```
~:: cat ~/.jupyter/jupyter_notebook_config.py 
c.GitHubConfig.access_token = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
```

Still only public repos are listed for the organization in jupyterlab.

**Comment by memeplex** [comment]
Here are some more details. The organization in question is `jampp`. I can access `jampp/gcd` but trying to access `jampp/daat` shows me:

![image](https://user-images.githubusercontent.com/2845433/64459103-7fa67800-d0cd-11e9-8438-c2c42e97ce3d.png)

`jampp` is an organization name. My user is `memeplex`. Still, trying to access `memeplex/daat` shows me that `memeplex` is not a user name.

**Comment by ian-r-rose** [comment]
@memeplex Can you try just putting the org name in the box, rather than `org/repo`?

**Comment by memeplex** [comment]
The problem with doing that was simply that private repos weren't listed at all. But I found out the problem: I had to install the server side part of the extension. Now it works as expected. Thank you!

**Comment by ian-r-rose** [comment]
Glad to hear you got it working @memeplex

**Comment by thbeh** [comment]
@memeplex could you describe how you install the server side part of the extension as I tried from README page but still unable to list my private repo. (Note-I am not using the enterprise github)

**Comment by memeplex** [comment]
AFAICR I just followed the instructions in the README. Sorry I can't say anything more useful than that.
