### ISSUE TITLE
Config option `client_id` not recognized by `GitHubConfig`

### ISSUE THREAD

**Issue by michaelaye** [jupyterlab/jupyterlab-github#94]
I had this running fine for a while, but since a few weeks ago, I'm getting this error in my server log, despite the fact that browsing user's GitHub repos actually works?

```bash
/Users/klay6683/miniconda3/envs/py37/lib/python3.7/site-packages/traitlets/config/configurable.py:84: UserWarning: Config option `client_id` not recognized by `GitHubConfig`.
  self.config = config
/Users/klay6683/miniconda3/envs/py37/lib/python3.7/site-packages/traitlets/config/configurable.py:84: UserWarning: Config option `client_secret` not recognized by `GitHubConfig`.
  self.config = config
```

I have an OAuth configured and have c.GitHubConfig.client_id and c.GitHubConfig.client_secret defined in `jupyter_notebook_config.py`.

My Jlab version is 1.1.4 and I have updated to the latest jupyterlab-github via the Jlab extension manager plugin.

**Comment by ian-r-rose** [comment]
The `client_id`/`client_secret` based approach had been deprecated for a while, and was removed in version 1.0 of this extension. That method of authentication wasn't really meant for end-users, and was a poor fit here.

The approach you now need to take is to make a personal access token: https://github.com/jupyterlab/jupyterlab-github#2-getting-your-credentials-from-github

Let me know if this doesn't solve your problem.

**Comment by ian-r-rose** [comment]
(I also should update the README to remove the deprecated approach)

**Comment by michaelaye** [comment]
> (I also should update the README to remove the deprecated approach)

That's exactly why I thought it was still okay. I will change my setup, thanks!

**Comment by ian-r-rose** [comment]
Okay, sorry for the confusion!

**Comment by michaelaye** [comment]
No worries, I should have paid attention to the word "Deprecated" more!
