### ISSUE TITLE
Github deprecation notice

### ISSUE THREAD

**Issue by michaelaye** [jupyterlab/jupyterlab-github#96]
Hi!
First, thanks for your software!
I used it today to browse the public repos of a github user and subsequently received this deprecation notice in my email:

> On February 5th, 2020 at 23:32 (UTC) your personal access token using JupyterLab GitHub was used as part of a query parameter to access an endpoint through the GitHub API:
https://api.github.com/
Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated.
Depending on your API usage, we'll be sending you this email reminder once every 3 days for each token and User-Agent used in API calls made on your behalf.
Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.
Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.
Thanks,
The GitHub Team

I'm using jupyterlab-github 1.0.0 and jupyterlab 1.2.6.

**Comment by ian-r-rose** [comment]
Thanks for flagging this @michaelaye!

**Comment by ian-r-rose** [comment]
This should be fixed in v2.0 of this extension. If anyone sees this notice with the most recent version, please let me know and we can reopen.

**Comment by michaelaye** [comment]
Just created a brand new access token for my linux box, where I'm using 2.0:

```
@jupyterlab/github v2.0.0  enabled  OK
```

and promptly after using it I got the deprecation notice email.

**Comment by ian-r-rose** [comment]
Can you try upgrading the python package?

**Comment by bkandel-edf** [comment]
@michaelaye I had the same issue today even with version 2.0 of the jupyterlab extension.
However, I noticed that the python package jupyterlab_github was still version 1.0.

I upgraded it to version 2.0 using
`pip install jupyterlab_github --upgrade`

Since Github email is a monthly notification, I'll have to wait a month to confirm this solved it, but that was a missing piece for me...
